{% set name = "pynldas2" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynldas2-{{ version }}.tar.gz
  sha256: c160639b4c38e4649f93cfd5b8220ad8e279d9623579c91ea609af08a1abfc45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >=3.8
    - async-retriever <0.18,>=0.17
    - h5netcdf
    - numpy >=1.21
    - pandas >=1.0
    - pygeoutils <0.18,>=0.17
    - pyproj >=2.2
    - rioxarray >=0.11
    - xarray >=2022.03.0

test:
  imports:
    - pynldas2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynldas2
  summary: Get NLDAS2 forcing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
