{% set name = "pynldas2" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynldas2-{{ version }}.tar.gz
  sha256: fb7561bf99beebb0b9d809b511d0d1ff99087f483af932cab185d7bd4f0f4fa1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - async-retriever >=0.3.10
    - h5netcdf
    - numpy >=1.21
    - pandas >=1.0
    - pygeoutils >=0.13.11
    - pyproj >=2.2
    - rioxarray >=0.11
    - xarray >=2022.03.0

test:
  imports:
    - pynldas2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynldas2
  summary: Get NLDAS2 forcing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
