{% set name = "pynldas2" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pynldas2-{{ version }}.tar.gz
  sha256: 7fecc2b511469d2630441d9ff285fe9d66e474d2763e21ea00a2b4965f96b26c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever =0.15
    - h5netcdf
    - numpy >=1.21
    - pandas >=1.0
    - pygeoutils =0.15
    - pyproj >=2.2
    - rioxarray >=0.11
    - xarray >=2022.03.0

test:
  imports:
    - pynldas2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pynldas2
  summary: Get NLDAS2 forcing data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
